### PR TITLE
Add plotting functions to visualize RNA velocities

### PR DESCRIPTION
**Pull request by mbstadler**
Thanks for the wonderful `velociraptor` package!

This PR adds two visualization functions (`plotVelocity` and `plotVelocityStream`), similar to the original `scvelo.pl.velocity` and `scvelo.pl.velocity_embedding_stream`). I think functions for visualization would be a useful addition to `velociraptor`.

I have tried to keep the dependencies low. However, the streamline function is based on `metR::geom_streamline`, and thus uses `ggplot2`. I did not manage a selective import of just the used functions from `ggplot2` without breaking `metR::geom_streamline`, and therefore had to add `ggplot2` to the "Depends" (maybe you see a way to avoid that).

I was also thinking about keeping the visualization functions in a separate package, to keep dependencies in check. However, I think that most use cases that involve estimation of RNA velocities would also use visualizations.

### CODE REVIEW

**Comment by LTLA** [comment]
It looks good, but all visualization functions should only `Suggest` their dependencies; see e.g. **SingleR** for an example.

Can you describe exactly what the problem is?

**Comment by mbstadler** [comment]
The problem is that `metR::geom_streamline` does not work unless `ggplot2` is loaded with `library(ggplot2)`. It will complain about missing functions (e.g. `ggplot2::coord_munch`), and importing them with `#' importFrom(ggplot2, coord_munch)` in `velociraptor` does not help. I guess the `metR` developer assumes that `metR::geom_streamline` would not be used without `ggplot2` being loaded.

I have looked at `SingleR` and think that a similar solution could work here, too, but I would probably use `if (!require(ggplot2)) {stop(...)}` at the top because `ggplot2::ggplot(...) + metR::geom_streamline(...)` will fail without a not so informative error (`could not find function coord_munch`).

If `ggplot2` is moved to suggests, should the unit tests then also be wrapped in a `if(require(ggplot2)) {...}`?

**Comment by LTLA** [comment]
> I have looked at `SingleR` and think that a similar solution could work here, too, but I would probably use `if (!require(ggplot2))`

That's fine, but while you do that, maybe you could also post an issue on the **metR** repo and see if the maintainer would be willing to use `ggplot2::coord_munch` (and similarly for whatever else is problematic for us). I only see one offending instance in `geom_streamline.R` where `coord_munch` is used without qualification.

**Comment by mbstadler** [comment]
I have posted an issue on the **metR** repo (https://github.com/eliocamp/metR/issues/133), and moved the plotting dependencies to `Suggest`.

**Comment by mbstadler** [comment]
The issue of the "missing coord_munch" has just been fixed upstream in the development branch of **metR**: https://github.com/eliocamp/metR/issues/133

**Comment by LTLA** [comment]
Excellent. 

At first glance, the PR seems fine. I will take a closer look at this later in the week, hopefully by that time the **metR** fix will also find its way onto CRAN.

**Comment by mbstadler** [comment]
Sounds good. 

Regarding the **metR**: I guess this will not make a difference anymore for this PR, now that we are not importing from it and from **ggplot2** anymore.

**Comment by LTLA** [comment]
Some comments:

- If `plotVelocityStream` uses **ggplot2**, why does `plotVelocity` use base graphics? We're already paying the dependency cost for **ggplot2** here, so you might as well re-use it for `plotVelocityStream`.
- All the `stopifnot()` checks are unnecessary and tedious to read through. Many of these will be caught by downstream functions anyway. Only add explicit error checks if the downstream functions take too long or yield confusing error messages (or when interfacing with native code where errors lead to segmentation faults - not relevant here).
- Similarly, there is no need to check for valid colors, downstream functions will catch those problems.
- Many of the functions added to `utils.R` are not generally reusable utilities. These should live in `plotVelocity.R`.
- In `plotVelocity`'s documentation, `@return` should describe the side-effect of the plotting function, i.e., to generate a plot on the current graphics device. Or a ggplot object, see my first point.
- Avoid non-standard evaluation in the ggplot construction. Use either `aes_string` or - given that is soft-deprecated - the new recommended `sym()` business, e.g.

```r
            metR::geom_streamline(mapping = ggplot2::aes(x = !!ggplot2::sym("x"), y = !!ggplot2::sym("y"), dx = dx, dy = dy,
```
- On a similar note, I don't know where `..dy..`, `..dx..` come from; these are not present in the input DF.
- Color, not colour; the codebase uses US English.

**Comment by mbstadler** [comment]
Here are additional changes based on your feedback:

- replace "colour" by "color" (I used colour initially for consistency with scater::plotReducedDim(..., colour_by))
- use ggplot2::sym() in ggplot2::aes
- move helpers only used by `plotVelocity` from `utils.R` to `plotVelocity.R` (same for corresponding tests)
- remove or replace checks for valid colors
- remove redundant `stopifnot()` checks (kept some where incorrect input might go unnoticed)
- rewrote `plotVelocity` to use `ggplot2` instead of base graphics (adds **patchwork** to Suggests)
- `..dx..` and `..dy..` are computed internally by `metR::geom_streamline`, and !!ggplot2::sym() does not work with them

Regarding the **metR** fix: At the moment, I think it is not needed because of https://github.com/mbstadler/velociraptor/blob/c2ec4fddda6206139abd6ff018b6eb239eee9ad3/R/plotVelocityStream.R#L111 (that's what I meant above). But I agree, once the **metR** fix is propagated to cran, we can replace `require` by `requireNamespace` in the above statement.

**Comment by LTLA** [comment]
Looking better and better. But we will need to think of a way to deal with `..dx..`. `check` won't be happy with these weird symbols appearing out of nowhere. (I don't know where `..step..` comes from either, for that matter. Just mysteriously appears.) 

The following works but is hardly "tidy". Or even particularly comprehensible.

```r
color = !!rlang::parse_quo("sqrt(..dx..^2 + ..dy..^2)", env=parent.frame())
```

Quite a pickle. This particular design choice of `geom_streamline` seems pretty awkward; for example, it won't handle the case where I have my own `..step..` variable in the calling environment/`data.frame` that I want to use instead of their calculated value.

**Comment by mbstadler** [comment]
I have added the `!!rlang::parse_quo("sqrt(..dx..^2 + ..dy..^2)", env=rlang::caller_env()))` to hide the non-standard evaluation from `check`.
I agree that this is not particularly comprehensible, and I would probably go with the NOTE in `check` instead of that. However I prefer the pickle over droping the double dot variables. I do think that using the internally calculated aesthetics help the visual interpretation of the velocity stream plot.

I don't think there is a danger of picking the wrong aesthetic: Double-dot variables (`..x..`) are used by **ggplot2** to discriminate calculated from mapped aesthetics. Appart from the fact that our data frame is constructed within the function and unlikely to ever contain a column of that name, it seems that the double-dot syntax causes **ggplot2** to use the calculated aesthetic, even if a column of the same name (either "dx" or "..dx..") exists in the provided data frame.

I also don't think that these internally calculated aesthetics are likely to disappear. `metR::geom_streamline` documents `dx`, `dy` and `step` here: https://eliocamp.github.io/metR/reference/geom_streamline.html.

Instead of the `..dx..`, `..dy..` and `..step..`, I also tried the alternative `ggplot2::stat(dx)`, which however does not work with `!!ggplot2::sym("dx")`.

**Comment by mbstadler** [comment]
I don't know why the vignette building suddenly fails on GHA (I have not touched the vignette or the code called from the failing block). I trigger a new build to see if this is something temporary.

**Comment by LTLA** [comment]
Some further fiddling reveals another take on the call that seems to work:

```r
color = ggplot2::stat(sqrt((!!ggplot2::sym("..dx.."))^2 + (!!ggplot2::sym("..dy.."))^2))
``` 

Longer but arguably easier to understand as the only new concept here is the `stat()`.

Off topic: I didn't realize that double-dots were a general convention for **ggplot2**. That is a little concerning - another gotcha that I have to remember. Unfortunately, "unlikely" is not "impossible" from a programming perspective.

**Comment by LTLA** [comment]
@kevinrue to review, it looks in a reasonably good shape.

**Comment by mbstadler** [comment]
I have added the `ggplot2::stat` call.

**Comment by mbstadler** [comment]
`check` still fails with:
```
Quitting from lines 74-77 (userguide.Rmd) 
Error: processing vignette 'userguide.Rmd' failed with diagnostics:
error in running command
```
I am not sure what to do about that (I cannot reproduce it locally). Could it be unrelated to this PR?

**Comment by LTLA** [comment]
Hopefully is fixed by **basilisk.utils** 1.3.7. **rappdirs** updated last week, with a major change being that the returned cache path now includes `~`; this broke a bunch of packages that didn't perform path expansion.

**Comment by kevinrue** [comment]
I'm trying to test this in the background, while working on other deadlines.
I've also been having a few issues due to bad interactions between my `renv` and Python setup, which impact my ability to test velociraptor. I'll keep you posted.

**Comment by kevinrue** [comment]
Alright, so finally, in my hands, R CMD succeeded for cd50a2852724861446a35a87a2a948afb51dde72 (macOS)
Debugging the GitHub Action will take more time. I'm actually tempted to switch to `biocthis::use_bioc_github_action()`, though it's so different that I'm not sure about all the implications yet.

**Comment by mbstadler** [comment]
@kevinrue Is there something that I can still do to help sorting the PR?

**Comment by kevinrue** [comment]
I'm checking one last time this weekend. Sorry for being a bit out of touch recently.

**Comment by kevinrue** [comment]
I just noticed

```
* checking dependencies in R code ... NOTE
'library' or 'require' call to 'ggplot2' in package code.
  Please use :: or requireNamespace() instead.
  See section 'Suggested packages' in the 'Writing R Extensions' manual.
```

I gotta get away from the computer for a bit, but I'll see what that's about if no one gets to it first.

**Comment by kevinrue** [comment]
> But I agree, once the **metR** fix is propagated to cran, we can replace `require` by `requireNamespace` in the above statement.

I just realise that this was mentioned earlier in this conversation. Fixed.

**Pull request merged**
