### PR TITLE
Adaptations to scVelo pipeline

### PR DESCRIPTION
**Pull request by csoneson**
Suggestions based on the following observations: 

* AnnData objects are transposed compared to SCEs
* As far as I have been able to deduce from the `scVelo` code, the normalized counts are not log-transformed before being used for modelling (only `X` is log-transformed)
* Addition of a way to support providing arguments to the `scVelo` functions

### CODE REVIEW

**Comment by LTLA** [comment]
Looks fine. If you could figure out how to plug in our own PCA and NN results into the `anndata` object, that would be a big plus and would finish off this particular wrapper.

**Comment by LTLA** [comment]
> * but the PCA calculations in `scVelo` (which will be called if there's no PCA in there already) assumes that `X` is log-transformed.

Hold on, is `X` distinct from `spliced`? They're not the same thing?

> I'm not sure about the neighbors though. 

Well, it's not like we can't get the distances either. Having said that, I don't mind leaving it to **scVelo** because most of the NN calculations in the rest of our functions are purely internal anyway.

> * Currently, `scvelo_anndata2sce` drops the row/column names, even if they are there before

To be replaced by @lazappi's thing at https://github.com/theislab/zellkonverter/.

> * I set the default `sf.spliced` to NULL, to make sure that it's consistent with the spliced count matrix (in many cases, this will not be `counts`).

Okay. See point 1 above.

**Comment by csoneson** [comment]
> Hold on, is X distinct from spliced? They're not the same thing?

Well, it can be, or not. The velocity quantification methods return two matrices (spliced and unspliced), and the spliced one is not the same as you would get if you just quantified gene expression "as usual" (which may be what you want to have in `X` if you want consistency with other parts of the analysis pipeline for dimension reduction etc).

**Comment by LTLA** [comment]
Ugh. Well, okay. If not supplied, we should compute reduced dimensions with **BiocSingular** (based on `subset.row`, the `counts`-derived log-expression matrix, and `BSPARAM=`).

We'll also need _another_ matrix in `x` for the counts, then, not just the spliced and unspliced.

Did that **scRNAseq** pipeline have a counts matrix? I only saw spliced and unspliced.

**Comment by csoneson** [comment]
Ok. 

> Did that scRNAseq PR you made have a counts matrix? I only saw spliced and unspliced.

No, it contained the spliced and unspliced counts. I think the choice of `X` is largely independent of the velocity calculations - you may want to use the spliced matrix, the sum of the spliced and unspliced, or a matrix obtained by an independent pipeline.

**Comment by LTLA** [comment]
How different are the spliced counts different from the normal counts? In principle, it seems like it would just be the usual exonic coverage or **salmon**'s equivalent to it.

On a related note, I also assume that the unspliced counts are just obtained by using the entire length of the gene as a single feature.

**Comment by csoneson** [comment]
> How different are the spliced counts different from the normal counts? In principle, it seems like it would just be the usual exonic coverage or salmon's equivalent to it.

Depends on how you define the spliced and normal counts :) usually the difference is not enormous if run with the same tool etc, but for the velocity quantification, exons and introns will compete for the reads falling in ambiguous regions. Example for the spermatogenesis data set, nonzero counts for the first 100 cells, regular counts on x, spliced on y: 

Screen Shot 2020-06-11 at 08 31 34

> On a related note, I also assume that the unspliced counts are just obtained by using the entire length of the gene as a single feature.

No. For the scRNAseq dataset, unspliced counts were obtained by providing both transcript and intron sequences to alevin for quantification, and then adding up counts for each of the two categories to the gene level. Described here (includes also a comparison to "gene body - gene expression" counts from STARsolo): https://www.biorxiv.org/content/10.1101/2020.03.13.990069v1

**Comment by LTLA** [comment]
Can't say I understand how Starsolo manages to get non-zero intronic counts for genes with no introns, but whatever. I'll need fit that citation into my caveats paragraph on RNA velocity.

**Comment by csoneson** [comment]
> Can't say I understand how Starsolo manages to get non-zero intronic counts for genes with no introns, but whatever. 

My interpretation is that in this case it's a difference in what they consider a valid overlap for the gene expression and gene body count. The latter includes reads partly overlapping the gene, while the former doesn't.

**Comment by csoneson** [comment]
> We'll also need another matrix in x for the counts, then, not just the spliced and unspliced. Similar modifications would be required for the S(C)E methods.

@LTLA - any preference for the name of this assay? `assay.counts`, `assay.exprs` (since they are all counts), `assay.x` (since it will go into the `X` slot of the AnnData object)?

**Comment by kevinrue** [comment]
My humble vote, this sounds the most intuitive:
> assay.x (since it will go into the X slot of the AnnData object)

Especially since they're all counts, we might as well disambiguate their respective purpose.

**Comment by LTLA** [comment]
Makes sense to me.

**Comment by LTLA** [comment]
Sounds like we're done here?

**Comment by csoneson** [comment]
Well, I think it works. Still lacks tests and a vignette though.

**Comment by LTLA** [comment]
That's okay, there's no tests or vignettes for anything ATM.

**Pull request merged**
