### PR TITLE
add example for scvelo.params argument

### PR DESCRIPTION
**Pull request by ATpoint**
I personally found it unintuitive how to use the scvelo.params argument. I think a little example like this will help others clarifying this.

### CODE REVIEW

**Comment by kevinrue** [comment]
Thanks, and very good point. I'm letting the CI checks run and I'll merge (probably tomorrow in my morning)

**Review by kevinrue — COMMENTED** [review]
Can you just set 'r' to 'devel' in this line and the next two please?

https://github.com/ATpoint/velociraptor/blob/patch-3/.github/workflows/check-bioc.yml#L55

**Comment by kevinrue** [comment]
Good to see one pass. I'm a bit puzzled (and short on time) to investigate the other two. Looks like the code passes fine the Bioconductor daily build. Ugh.

**Comment by csoneson** [comment]
Thanks @ATpoint - just to expand a bit on the failing runs: I'm also not sure why the mac one fails, but the ubuntu one uses the wrong combination of R and Bioc. I think we need the following configuration in the workflow yml: 
```
- { os: ubuntu-latest, r: 'devel', bioc: 'devel', cont: "bioconductor/bioconductor_docker:devel", rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest" }
- { os: macOS-latest, r: 'devel', bioc: 'devel'}
- { os: windows-latest, r: 'devel', bioc: 'devel'}
```

Also, could you run `devtools::document()` and push the .Rd file so that your changes make it into the documentation?

**Comment by ATpoint** [comment]
Ok, made these changes. Sorry that this little PR makes such a fuzz.

**Comment by kevinrue** [comment]
Nothing to be sorry about. Typical minor updates to the testing environment that are not directly related to the package functionality. Thanks for your patience :)

**Comment by kevinrue** [comment]
Quick note to point out that I haven't forgotten about this. I just have one other time sensitive thing to finish first. 

This is one of those things that can be fixed in either 5 min or 5 days, trying out different configurations and waiting for CI to run, and I'd rather do it when I can properly focus on the appropriate clean fix.

**Comment by kevinrue** [comment]
it seems to be working when I push your branch to the main repo, with a little extra commit that @csoneson suggested.
Basically just about running `devtools::document()`
See here for the commit history: https://github.com/kevinrue/velociraptor/commits/patch-3

I tried pushing to your branch but apparently edits on your PR are disabled. Can you add that commit yourself? Otherwise I'll have to close your PR and make a new one from my copy of the branch

**Comment by ATpoint** [comment]
I already pushed the updated Rd files https://github.com/kevinrue/velociraptor/pull/56/commits/860f4bd2c6c0f33ee122aff352a01336ff742264

Anyway, feel free to close and make a PR from your branch :)

**Comment by kevinrue** [comment]
That's odd, because I pulled your branch and a file still got updated when I ran roxygen. Anyway, yes, I'll do it. Your contributing commits will still make it in the log and be acknowledged :) Thanks!

**Comment by kevinrue** [comment]
Fixed by #57 
Thanks for doing all the leg work @ATpoint !

**Pull request closed without merging**
